# Generated by Django 4.2.2 on 2023-06-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='snacks',
            old_name='reviewer',
            new_name='purchaser',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='rating',
        ),
    ]
